name: Build
on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main
  workflow_dispatch:

env:
  IMAGE_REGISTRY: ghcr.io/${{ github.repository_owner }}
  IMAGE_NAME: aurora-oci

jobs:
  build_push:
    name: Build and push image
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      id-token: write

    steps:
      - name: Checkout
        uses: actions/checkout@1af3b93b6815bc44a9784bd300feb67ff0d1eeb3 # v6

      - name: Build Image
        id: build
        run: |
          buildah build -t ${{ env.IMAGE_NAME }}:latest -f ./Containerfile .

      - name: Login to GitHub Container Registry
        if: github.event_name != 'pull_request'
        run: |
          echo "${{ secrets.GITHUB_TOKEN }}" | podman login -u "${{ github.actor }}" --password-stdin ghcr.io

      - name: Push Image
        if: github.event_name != 'pull_request'
        run: |
          podman push ${{ env.IMAGE_NAME }}:latest ${{ env.IMAGE_REGISTRY }}/${{ env.IMAGE_NAME }}:latest

      # - name: Install Cosign
      #   uses: sigstore/cosign-installer@7e8b541eb2e61bf99390e1afd4be13a184e9ebc5 # v3.10.1
      #   if: github.event_name != 'pull_request'

      # - name: Sign container image
      #   if: github.event_name != 'pull_request'
      #   run: |
      #     cosign sign -y --key env://COSIGN_PRIVATE_KEY ${{ env.IMAGE_REGISTRY }}/${{ env.IMAGE_NAME }}:latest
      #   env:
      #     COSIGN_EXPERIMENTAL: false
      #     COSIGN_PRIVATE_KEY: ${{ secrets.SIGNING_SECRET }}
